In [2]:
import numpy as np
a=np.arange(16).reshape(4,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
x=[True,False,False,True]
a[:,x]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15]])

In [8]:
np.any(a==1)

True

In [9]:
np.any(a<0)

False

In [10]:
np.all(a>0)

False

In [11]:
np.all(a>=0)

True

In [12]:
np.sum(a%2==0,axis=1)

array([2, 2, 2, 2])

In [13]:
np.all(a%2==0,axis=1)

array([False, False, False, False])

In [15]:
np.sum((a>3)&(a<10))

6

In [16]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [17]:
a[a[:,-1]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [19]:
x=[1,2,3]
y=[0,1,2]
a[x,y]

array([ 4,  9, 14])