In [1]:
from  sklearn import datasets
import numpy as np


In [3]:
iris=datasets.load_iris()
X=iris.data
y=iris.target
shuffle_indexes=np.random.permutation(len(X))
shuffle_indexes

array([ 11,  72, 127,  76,  42,  31,   2,  48, 145,  20,  43, 116,  46,
        93,  83,  29, 100,  58,  78,  27,  91,  82,  49,  36,  69,  47,
        88,  57,  73,   9,  16, 101,  64,  84,  12,   0,   7, 149,  98,
        87, 130,  41,  18,  97,  33,  24, 125,  66,  50,  59, 102,  52,
        70, 134, 113,  60, 147,   8, 106, 107, 126,  86,  19, 118,  10,
        74,  14,   4, 117, 139,  17, 124,  13,  62,  94,  90,  45,  96,
        37, 137,   1,  67,  30, 115,  92,  51, 111,  79, 114, 143, 146,
       112,  56,  53, 141, 110, 136,  22, 133,   3, 122,  25,  63, 119,
       140,  77,  89, 132,  44, 105,  34, 138,  23,   5,  55,  99,  21,
       142,  80,  54,  61,  32,  95,  40,  39,   6,  26,  71,  15, 120,
       131, 128, 135,  28,  75, 121, 108, 129,  68, 109, 123, 148,  38,
        65,  81, 144, 103,  85,  35, 104])

In [4]:
test_ratio=0.2
test_size=int(test_ratio*len(X))
test_size

30

In [5]:
test_indexes=shuffle_indexes[:test_size]
test_indexes

array([ 11,  72, 127,  76,  42,  31,   2,  48, 145,  20,  43, 116,  46,
        93,  83,  29, 100,  58,  78,  27,  91,  82,  49,  36,  69,  47,
        88,  57,  73,   9])

In [6]:
train_indexes=shuffle_indexes[test_size:]
train_indexes

array([ 16, 101,  64,  84,  12,   0,   7, 149,  98,  87, 130,  41,  18,
        97,  33,  24, 125,  66,  50,  59, 102,  52,  70, 134, 113,  60,
       147,   8, 106, 107, 126,  86,  19, 118,  10,  74,  14,   4, 117,
       139,  17, 124,  13,  62,  94,  90,  45,  96,  37, 137,   1,  67,
        30, 115,  92,  51, 111,  79, 114, 143, 146, 112,  56,  53, 141,
       110, 136,  22, 133,   3, 122,  25,  63, 119, 140,  77,  89, 132,
        44, 105,  34, 138,  23,   5,  55,  99,  21, 142,  80,  54,  61,
        32,  95,  40,  39,   6,  26,  71,  15, 120, 131, 128, 135,  28,
        75, 121, 108, 129,  68, 109, 123, 148,  38,  65,  81, 144, 103,
        85,  35, 104])

In [8]:
X_train=X[train_indexes]
y_train=y[train_indexes]


In [ ]:
X_test=X[test_indexes]
y_test=y[test_indexes]