In [1]:
import numpy as np
np.random.seed(666)
a=np.random.normal(size=1000000)

In [2]:
np.min(a)

-4.769787080001609

In [4]:
np.argmin(a)  #最小值所在的索引

971892

In [5]:
a[971892]

-4.769787080001609

In [11]:
b=np.arange(16)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.random.shuffle(b)
b

array([15,  1,  3,  7,  9, 14, 13,  6, 11,  5,  4,  0,  2, 10,  8, 12])

In [13]:
np.sort(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
b.sort()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
np.random.shuffle(b)
np.partition(b,3)

array([ 0,  2,  1,  3,  5,  4,  6,  8,  9, 10,  7, 11, 13, 15, 14, 12])