In [7]:
import numpy as np
np.random.seed(666)
a=np.random.random(size=100)
a

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796,
       0.0127032 , 0.4135877 , 0.04881279, 0.09992856, 0.50806631,
       0.20024754, 0.74415417, 0.192892  , 0.70084475, 0.29322811,
       0.77447945, 0.00510884, 0.11285765, 0.11095367, 0.24766823,
       0.0232363 , 0.72732115, 0.34003494, 0.19750316, 0.90917959,
       0.97834699, 0.53280254, 0.25913185, 0.58381262, 0.32569065,
       0.88889931, 0.62640453, 0.81887369, 0.54734542, 0.41671201,
       0.74304719, 0.36959638, 0.07516654, 0.77519298, 0.21940924,
       0.07934213, 0.48678052, 0.1536739 , 0.82846513, 0.19136857,
       0.27040895, 0.56103442, 0.90238039, 0.85178834, 0.41808196,
       0.39347627, 0.01622051, 0.29921337, 0.35377822, 0.89350267,
       0.78613657, 0.77138693, 0.42005486, 0.77602514, 0.46430814,
       0.18177017, 0.8840256 , 0.71879227, 0.6718813 , 0.25656363,
       0.43080182, 0.01645358, 0.23499383, 0.51117131, 0.29200924,
       0.50189351, 0.49827313, 0.10377152, 0.44644312, 0.96918

In [8]:
np.sum(a)

49.20482630064384

In [9]:
np.max(a)

0.9987946727616922

In [10]:
np.min(a)

0.003909843867777485

In [11]:
b=np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(b)

120

In [13]:
A=np.array([[1,2,3],[4,5,6]])
np.concatenate([A,A])
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [16]:
np.sum(b,axis=1)

array([ 6, 22, 38, 54])

In [18]:
np.prod(b+1)

20922789888000

In [19]:
np.mean(b)

7.5

In [20]:
np.median(b)

7.5

In [21]:
np.percentile(a,q=50)

0.4925268257272435

In [22]:
np.var(a)  #方差

0.09207321190717986

In [23]:
np.std(a) #标准差

0.3034356800166715

In [25]:
c=np.random.normal(loc=0,scale=1,size=1000000)

In [26]:
np.std(c)

0.9997317536099986

In [28]:
np.mean(c)

0.0013511028715323193